apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: 80
    targetPort: vproapp-port # same in vproappdep.yaml in line 22 - name: vprgapp-port
    protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer # it will lunuch elastic load balancer 